CREATE TABLE IF NOT EXISTS vouchers (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, branch_id uuid NOT NULL REFERENCES branches(id), kind text NOT NULL CHECK (kind IN ('receipt','payment')), subtype text NOT NULL CHECK (subtype IN ('customer','supplier','expense','account','salary','vat','other')), number text, date date NOT NULL, party_id uuid REFERENCES parties(id), counter_account_id uuid REFERENCES accounts(id), cash_location_id uuid NOT NULL REFERENCES cash_locations(id), method text NOT NULL CHECK (method IN ('cash','cheque','bank_transfer','card')), amount numeric(20,4) NOT NULL CHECK (amount > 0), vat_amount numeric(20,4) NOT NULL DEFAULT 0, net_amount numeric(20,4) NOT NULL DEFAULT 0, currency text NOT NULL DEFAULT 'SAR', fx_rate numeric(20,10), cheque_no text, cheque_date date, bank_name text, cheque_state text CHECK (cheque_state IS NULL OR cheque_state IN ('pending','cleared','bounced','collected')), cost_center_id uuid REFERENCES cost_centers(id), reference_no text, reference_date date, recipient text, status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','posted','voided')), journal_entry_id uuid REFERENCES journal_entries(id), fiscal_period_id uuid REFERENCES fiscal_periods(id), posted_at timestamptz, voided_at timestamptz, idempotency_key text, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_at timestamptz, updated_by uuid, version int NOT NULL DEFAULT 1, legacy_source text, legacy_id text);
CREATE UNIQUE INDEX IF NOT EXISTS vouchers_tenant_number_key ON vouchers(tenant_id, number) WHERE number IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS vouchers_tenant_idempotency_key ON vouchers(tenant_id, idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS vouchers_scope_idx ON vouchers(tenant_id, branch_id, status, kind);
CREATE INDEX IF NOT EXISTS vouchers_cash_idx ON vouchers(tenant_id, cash_location_id, posted_at);

CREATE TABLE IF NOT EXISTS cash_transfers (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, branch_id uuid NOT NULL REFERENCES branches(id), from_cash_location_id uuid NOT NULL REFERENCES cash_locations(id), to_cash_location_id uuid NOT NULL REFERENCES cash_locations(id), number text, amount numeric(20,4) NOT NULL CHECK (amount > 0), currency text NOT NULL DEFAULT 'SAR', status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','sent','received','voided')), sent_journal_entry_id uuid REFERENCES journal_entries(id), received_journal_entry_id uuid REFERENCES journal_entries(id), sent_at timestamptz, received_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_at timestamptz, updated_by uuid, version int NOT NULL DEFAULT 1, legacy_source text, legacy_id text, CHECK (from_cash_location_id <> to_cash_location_id));
CREATE UNIQUE INDEX IF NOT EXISTS cash_transfers_tenant_number_key ON cash_transfers(tenant_id, number) WHERE number IS NOT NULL;
CREATE INDEX IF NOT EXISTS cash_transfers_scope_idx ON cash_transfers(tenant_id, status);

CREATE TABLE IF NOT EXISTS expense_types (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, name_ar text NOT NULL, name_en text, account_id uuid NOT NULL REFERENCES accounts(id), cost_center_id uuid REFERENCES cost_centers(id), created_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_at timestamptz, updated_by uuid, version int NOT NULL DEFAULT 1, deleted_at timestamptz, deleted_by uuid, legacy_source text, legacy_id text);
CREATE UNIQUE INDEX IF NOT EXISTS expense_types_tenant_name_key ON expense_types(tenant_id, name_ar) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS shift_closes (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, branch_id uuid NOT NULL REFERENCES branches(id), user_id uuid NOT NULL, opened_at timestamptz NOT NULL DEFAULT now(), closed_at timestamptz, status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed','voided')), expected_cash numeric(20,4) NOT NULL DEFAULT 0, counted_cash numeric(20,4) NOT NULL DEFAULT 0, diff numeric(20,4) NOT NULL DEFAULT 0, summary jsonb NOT NULL DEFAULT '{}', report_html text, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid, updated_at timestamptz, updated_by uuid, version int NOT NULL DEFAULT 1);
CREATE UNIQUE INDEX IF NOT EXISTS shift_closes_one_open_key ON shift_closes(tenant_id, branch_id, user_id) WHERE status = 'open';
CREATE INDEX IF NOT EXISTS shift_closes_scope_idx ON shift_closes(tenant_id, branch_id, status);

CREATE TABLE IF NOT EXISTS shift_close_lines (shift_close_id uuid NOT NULL REFERENCES shift_closes(id) ON DELETE CASCADE, line_no int NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, kind text NOT NULL, method text, party_id uuid REFERENCES parties(id), amount numeric(20,4) NOT NULL DEFAULT 0, metadata jsonb NOT NULL DEFAULT '{}', PRIMARY KEY(shift_close_id, line_no));
CREATE TABLE IF NOT EXISTS cash_count_lines (shift_close_id uuid NOT NULL REFERENCES shift_closes(id) ON DELETE CASCADE, line_no int NOT NULL, tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, currency_code text NOT NULL DEFAULT 'SAR', denomination numeric(20,4) NOT NULL CHECK (denomination > 0), count int NOT NULL CHECK (count >= 0), total numeric(20,4) NOT NULL, PRIMARY KEY(shift_close_id, line_no));

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['vouchers','cash_transfers','expense_types','shift_closes','shift_close_lines','cash_count_lines'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t); EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t); EXECUTE format('DROP POLICY IF EXISTS %I_tenant_isolation ON %I', t, t); EXECUTE format('CREATE POLICY %I_tenant_isolation ON %I USING (tenant_id = current_setting(''app.tenant_id'', true)::uuid) WITH CHECK (tenant_id = current_setting(''app.tenant_id'', true)::uuid)', t, t); END LOOP; END $$;
