-- Phase 09 part two — 🧵 طلب التفصيل (`Form_WPF/frmOrders.xaml` + `frmOrderDetails.xaml`).
--
-- `frmOrders.xaml` («إدارة طلبات التفصيل») is a filter bar over one grid:
--
--   • filters — `txtSearch` (رقم الطلب or اسم العميل) · `cmbStatus`
--     (`DisplayMemberPath=StatusName`, `SelectedValuePath=StatusID`, the list is
--     `SELECT StatusID, StatusName FROM OrderStatus WHERE IsActive=1 ORDER BY
--     DisplayOrder` with «الكل» prepended at StatusID 0) · `dtFrom` · `dtTo` ·
--     «🔍 بحث».
--   • «📋 قائمة الطلبات» — `رقم الطلب · 👤 العميل · 📞 الجوال · القياس · نوع التفصيل ·
--     ⚙️ الحالة · 📅 تاريخ الطلب · 📅 موعد التسليم · 💰 السعر · 💵 المدفوع ·
--     ⌛ المتبقي` and «عدد السجلات: {n}».
--   • buttons — `✖ إغلاق` · `➕ إضافة طلب جديد` · `✏️ تعديل` · `🗑️ حذف` ·
--     `🔄 تغيير الحالة`, and a double-click opens تعديل.
--
-- `frmOrders.xaml.cs` is where the rules are:
--
--   • `LoadOrders` L73 — `SELECT * FROM vw_OrdersComplete WHERE 1=1` plus
--     `StatusID=@StatusID` when the combo is not «الكل» (0), `OrderDate>=@DateFrom`,
--     `OrderDate<=@DateTo`, and `(OrderNumber LIKE @Search OR CustomerName LIKE
--     @Search)`, then `ORDER BY OrderDate DESC`.
--   • delayed rows are painted `#FFE4E4` with dark-red text — the view's `IsDelayed`.
--   • `btnDelete_Click` L218 — «الرجاء اختيار طلب للحذف», then
--     «هل أنت متأكد من حذف هذا الطلب؟\nسيتم حذف جميع البيانات المرتبطة به», then
--     `DELETE FROM TailoringOrders WHERE OrderID=@ID` and «تم الحذف بنجاح».
--   • `btnChangeStatus_Click` L281 — «الرجاء اختيار طلب», a «تغيير حالة الطلب» window
--     («الحالة الحالية: …» · «الحالة الجديدة:» · «✔ تغيير», «الرجاء اختيار حالة جديدة»
--     if none is picked) then `sp_UpdateOrderStatus @OrderID, @NewStatusID, @ChangedBy`
--     and «تم تغيير الحالة بنجاح».
--
-- `frmOrderDetails.xaml` («إضافة طلب تفصيل») is the card:
--
--   • «👤 بيانات العميل» — search by name or mobile (`Customers`), «🔍 بحث»,
--     «الرجاء إدخال اسم أو جوال العميل» / «لم يتم العثور على عميل».
--   • «📋 تفاصيل الطلب» — `القياس` (`CustomerMeasurements` of that customer, the display
--     name falls back to «قياس بتاريخ …») · `نوع التفصيل` (`TailoringTypes`, each with a
--     `DefaultPrice`) · `موعد التسليم` · `الكمية` (1) · `السعر` · `المدفوع` ·
--     `المتبقي` (= السعر − المدفوع).
--   • «🔧 الخيارات» — `OptionCategories` × `OptionValues` per order (`OrderOptions`).
--   • «🧵 تفاصيل القماش والتصميم» — `نوع القماش` · `لون القماش` · `ملاحظات التصميم`.
--   • «💾 حفظ الطلب» / «✖ إلغاء», and the refusals «الرجاء اختيار عميل» ·
--     «الرجاء اختيار نوع التفصيل» · «الرجاء إدخال السعر» (when `price <= 0`).
--
-- The cloud's `tailoring` module answers «ما قياس هذا العميل؟» (`customer_measurements`)
-- and nothing else: there is no طلب, no حالة, no موعد تسليم, no سعر. Everything the
-- tailor writes on the card is added here. No column or endpoint that already exists is
-- renamed or removed.
--
-- Three decisions, because the desktop's `OrderStatus` / `TailoringTypes` /
-- `OptionCategories` rows are *data* and are not in this repository:
--
--   1. `OrderStatus` names are nowhere in the code — `frmOrders` only reads them. The one
--      place the tailoring lifecycle is written in words is `frmViewOrders.xaml.cs`
--      `GetStateText` L119: `0 مستلم · 1 في الخياطة · 2 جاهز · default تم التسليم`. The
--      four statuses below are seeded from it, in that order, by display_order.
--   2. `is_final` marks «تم التسليم». The desktop's `IsDelayed` is computed inside
--     `vw_OrdersComplete` (view body not in the repository); an order is delayed here when
--     موعد التسليم has passed and its status is not final — the same reading as the
--     red row paint.
--   3. `OrderNumber` is generated by the desktop's `sp_*` procedure (body not in the
--     repository). The number is allocated in the service from the tenant's document
--     sequence, like every other cloud document, with the prefix `TO-`.

CREATE TABLE IF NOT EXISTS tailoring_order_statuses (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants (id) ON DELETE cascade,
  code text NOT NULL,
  name_ar text NOT NULL,
  display_order integer NOT NULL DEFAULT 0,
  is_final boolean NOT NULL DEFAULT false,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  version integer NOT NULL DEFAULT 1,
  deleted_at timestamptz,
  deleted_by uuid
);

CREATE UNIQUE INDEX IF NOT EXISTS tailoring_order_statuses_tenant_code_key
  ON tailoring_order_statuses (tenant_id, code)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tailoring_order_statuses_tenant_idx
  ON tailoring_order_statuses (tenant_id, display_order);

COMMENT ON COLUMN tailoring_order_statuses.is_final IS
  '⚙️ الحالة النهائية — «تم التسليم»; an order whose موعد التسليم passed and is not final is «متأخّر»';

-- ⚙️ الحالات الأربع التي يعرفها الديسكتوب: مستلم · في الخياطة · جاهز · تم التسليم
INSERT INTO tailoring_order_statuses (id, tenant_id, code, name_ar, display_order, is_final)
SELECT
  gen_random_uuid(), tenants.id, seed.code, seed.name_ar, seed.display_order, seed.code = 'delivered'
FROM tenants
CROSS JOIN (
  VALUES ('received',  'مستلم',     1),
         ('sewing',    'في الخياطة', 2),
         ('ready',     'جاهز',      3),
         ('delivered', 'تم التسليم', 4)
) AS seed (code, name_ar, display_order)
WHERE NOT EXISTS (
  SELECT 1 FROM tailoring_order_statuses existing
   WHERE existing.tenant_id = tenants.id AND existing.code = seed.code
);

-- 🧵 نوع التفصيل — `TailoringTypes(TypeID, TypeName, DefaultPrice, IsActive)`
CREATE TABLE IF NOT EXISTS tailoring_types (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants (id) ON DELETE cascade,
  code text,
  name_ar text NOT NULL,
  default_price numeric(20, 4) NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  version integer NOT NULL DEFAULT 1,
  deleted_at timestamptz,
  deleted_by uuid
);

CREATE UNIQUE INDEX IF NOT EXISTS tailoring_types_tenant_name_key
  ON tailoring_types (tenant_id, name_ar)
  WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS tailoring_types_tenant_code_key
  ON tailoring_types (tenant_id, code)
  WHERE deleted_at IS NULL AND code IS NOT NULL;

-- 🔧 الخيارات — `OptionCategories(CategoryID, CategoryName, IsActive, DisplayOrder)`
CREATE TABLE IF NOT EXISTS tailoring_option_categories (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants (id) ON DELETE cascade,
  name_ar text NOT NULL,
  display_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  version integer NOT NULL DEFAULT 1,
  deleted_at timestamptz,
  deleted_by uuid
);

CREATE UNIQUE INDEX IF NOT EXISTS tailoring_option_categories_tenant_name_key
  ON tailoring_option_categories (tenant_id, name_ar)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tailoring_option_categories_tenant_idx
  ON tailoring_option_categories (tenant_id, display_order);

-- 🔧 الخيارات — `OptionValues(ValueID, CategoryID, ValueName, IsDefault, IsActive, DisplayOrder)`
CREATE TABLE IF NOT EXISTS tailoring_option_values (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants (id) ON DELETE cascade,
  category_id uuid NOT NULL REFERENCES tailoring_option_categories (id) ON DELETE cascade,
  name_ar text NOT NULL,
  is_default boolean NOT NULL DEFAULT false,
  display_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  version integer NOT NULL DEFAULT 1,
  deleted_at timestamptz,
  deleted_by uuid
);

CREATE UNIQUE INDEX IF NOT EXISTS tailoring_option_values_tenant_name_key
  ON tailoring_option_values (tenant_id, category_id, name_ar)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tailoring_option_values_category_idx
  ON tailoring_option_values (tenant_id, category_id, display_order);

-- 🧵 طلب التفصيل — `TailoringOrders` as read by `vw_OrdersComplete`
CREATE TABLE IF NOT EXISTS tailoring_orders (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants (id) ON DELETE cascade,
  number text NOT NULL,
  party_id uuid NOT NULL REFERENCES parties (id) ON DELETE restrict,
  measurement_id uuid REFERENCES customer_measurements (id) ON DELETE set null,
  type_id uuid NOT NULL REFERENCES tailoring_types (id) ON DELETE restrict,
  status_id uuid NOT NULL REFERENCES tailoring_order_statuses (id) ON DELETE restrict,
  order_date date NOT NULL,
  delivery_date date,
  quantity numeric(20, 4) NOT NULL DEFAULT 1,
  price numeric(20, 4) NOT NULL DEFAULT 0,
  paid_amount numeric(20, 4) NOT NULL DEFAULT 0,
  fabric_type text,
  fabric_color text,
  design_notes text,
  general_notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  version integer NOT NULL DEFAULT 1,
  deleted_at timestamptz,
  deleted_by uuid
);

CREATE UNIQUE INDEX IF NOT EXISTS tailoring_orders_tenant_number_key
  ON tailoring_orders (tenant_id, number)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tailoring_orders_tenant_date_idx
  ON tailoring_orders (tenant_id, order_date DESC);

CREATE INDEX IF NOT EXISTS tailoring_orders_tenant_party_idx
  ON tailoring_orders (tenant_id, party_id);

CREATE INDEX IF NOT EXISTS tailoring_orders_tenant_status_idx
  ON tailoring_orders (tenant_id, status_id);

COMMENT ON COLUMN tailoring_orders.paid_amount IS
  '💵 المدفوع — «المتبقي» is 💰 السعر − 💵 المدفوع, as `frmOrderDetails.CalculateRemaining` L290 prints it';

-- 🔧 الخيارات المختارة للطلب — `OrderOptions(OrderID, CategoryID, ValueID)`
CREATE TABLE IF NOT EXISTS tailoring_order_options (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants (id) ON DELETE cascade,
  order_id uuid NOT NULL REFERENCES tailoring_orders (id) ON DELETE cascade,
  category_id uuid NOT NULL REFERENCES tailoring_option_categories (id) ON DELETE cascade,
  value_id uuid NOT NULL REFERENCES tailoring_option_values (id) ON DELETE restrict,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz,
  updated_by uuid,
  version integer NOT NULL DEFAULT 1
);

CREATE UNIQUE INDEX IF NOT EXISTS tailoring_order_options_tenant_key
  ON tailoring_order_options (tenant_id, order_id, category_id);
